### ISSUE TITLE
Enhancement of Contact Us page

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT.github.io#104]

**Comment by Srijita-Mandal** [comment]
Can I contribute on this issue? Though there is no certain description provided, can I do this under mentorship and discussion?

**Comment by SabariGanesh-K** [comment]
I have relevant skills. Would love to take up this issue. Kindly assign it to me😀

**Comment by Adwipkashyap1234** [comment]
I want to contribute. Kindly assign it to me

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by PrajwalDhule** [comment]
hello, I would like to work on this issue

**Comment by Chaitalishetty** [comment]
@ZaidMujahid Assigning this issue to you . Happy Coding !

**Comment by ZaidMujahid** [comment]
Can you elaborate like what enhancement are required?

**Comment by ZaidMujahid** [comment]
@Chaitalishetty Can you please elaborate like what enhancement are required?

**Comment by Sanghu01** [comment]
I want to contribute in this issue .

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
i want to work in this issue under JWOC
