### ISSUE TITLE
Add Preloader 

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT.github.io#105]
Add an animated preloader for the website which should be related to the website theme

**Comment by sorba160** [comment]
I want to work on this issue , please allow me to do so. 
Thank you

**Comment by Devmindtk** [comment]
> Add an animated preloader for the website which should be related to the website theme

I would like to work on this issue @Chaitalishetty  please assign it to me.

**Comment by Chaitalishetty** [comment]
Do check the readme section.

**Comment by Jyotishman22** [comment]
I want to work on this issue , please allow me to do @Chaitalishetty THANK YOU

**Comment by sorba160** [comment]
I want to work on this issue , please allow me to do so @Chaitalishetty .
Thank you

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@sorba160 Assigning this issue to you . Happy Coding !

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@AtriSukul1508 @ZaidMujahid  @Srijita-Mandal Assigning you all this issue . Happy Coding !

**Comment by ZaidMujahid** [comment]
@Chaitalishetty You have assign this issue to all, which one will you consider then?

**Comment by Chaitalishetty** [comment]
I will merge the PR that looks the best!
You all also can also send your implementation on discord to confirm.
