### ISSUE TITLE
Add JWOC in opportunities page

### ISSUE THREAD

**Issue by SabariGanesh-K** [HackClubRAIT/HackClubRAIT.github.io#109]
**Describe the solution you'd like**
The opportunities page has Hactoberfest added. But this project has also participated in JWOC.But it's missing. Hence if approved, I would Jwoc under opportunities section. 

### Are you participating under any open-source program? ### 
Yes, JWOC

**Comment by SabariGanesh-K** [comment]
You can assign on feb 1.Sorry I thought today is feb 1 and opened it🤦‍♂️

**Comment by Chaitalishetty** [comment]
No worries @SabariGanesh-K you can close this issue and create a new issue tomorrow.

**Comment by SabariGanesh-K** [comment]
Assign to me👏👏.. If possible make it medium, I will enhance the page to make it responsive and friendly too

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@SabariGanesh-K you can add more open source opportunities like gsoc, gssoc, etc. Would be expecting minimum 3 more opportunities.Assigning you this issue. Happy coding!

**Comment by Chaitalishetty** [comment]
> Assign to me👏👏.. If possible make it medium, I will enhance the page to make it responsive and friendly too @Chaitalishetty

Yes go ahead!

**Comment by SabariGanesh-K** [comment]
> @SabariGanesh-K you can add more open source opportunities like gsoc, gssoc, etc. Would be expecting minimum 3 more opportunities.Assigning you this issue. Happy coding! 

Okayy. Sure. Thanks👍👏

**Comment by SabariGanesh-K** [comment]
Issue done and merged at #119 .
Hence closing it
