### ISSUE TITLE
Add animated background to the homepage of the website.

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT.github.io#120]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/66556168/152005854-538a2a38-0642-4aef-9d9e-e1fae0686c7e.png)
The background looks very simple try to add animation and make it interesting.

Also while taking up this issue mention how you are going to implement it!

**Comment by SabariGanesh-K** [comment]
I would like to take up this issue. I already have 2 , but I have completed issue #119 in this repo. So once you merge it , kindly assign this to me. I have relevant skills and can complete this. @Chaitalishetty

**Comment by riiyaaa** [comment]
I would love to work on it! I plan on making the page look more interactive in two ways:

- I will either add text animation or
- I will add background animation

**Comment by whiteHatpro** [comment]
i want to work in this issue under JWOC

**Comment by Chaitalishetty** [comment]
@riiyaaa Assigning you this issue . Happy coding !

**Comment by riiyaaa** [comment]
Added animated background. The transparent boxes will float upwards. 

![animated backdrop](https://user-images.githubusercontent.com/87305761/152322510-7dd478f3-acaa-4f6f-8e33-cb378209c55f.jpg)
