### ISSUE TITLE
Remove the margin on top

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT.github.io#126]
There is a margin on top in contributors, team and opportunities section in mobile view

![image](https://user-images.githubusercontent.com/66556168/152647312-aee8f1aa-e279-48f2-bc8e-368c8ede64ea.png)
![image](https://user-images.githubusercontent.com/66556168/152647359-14236fe7-9e57-4aa5-959d-162ad318929c.png)
![image](https://user-images.githubusercontent.com/66556168/152647383-4048a4df-bcf8-412d-a378-e576daee1a41.png)

**Comment by Yasshu55** [comment]
I would like to work on this

**Comment by Chaitalishetty** [comment]
@Yasshu55 Assigning this issue to you. Happy Coding !
