### ISSUE TITLE
Modify the Oppurtunities cards to look better

### ISSUE THREAD

**Issue by ronitblenz** [HackClubRAIT/HackClubRAIT.github.io#130]
Kindly, assign me to this issue

Thanks

**Comment by Chaitalishetty** [comment]
@ronitblenz Are you working under JWOC?

**Comment by ronitblenz** [comment]
Yes, I am

**Comment by ronitblenz** [comment]
Yeah sure, assign me

**Comment by ronitblenz** [comment]
Kindly check and merge me PR

**Comment by ronitblenz** [comment]
I have done the responsive thing, as directed, Plz merge my pr
