### ISSUE TITLE
Fix cards of opportunities page

### ISSUE THREAD

**Issue by khushimarothi** [HackClubRAIT/HackClubRAIT.github.io#165]
**Describe the bug**
The cards on the opportunities page are extremely big in size in desktop view and too slim in responsive view.

**Expected behavior**
I think the grid of three cards will look good and a bit smaller size that fits in desktop view will be suitable.

### Are you participating under any open-source program? ### 
Yes, HCSOC''22

**Comment by khushimarothi** [comment]
@Chaitalishetty

**Comment by Chaitalishetty** [comment]
@khushimarothi Assigning you this issue. Happy Coding!

**Comment by khushimarothi** [comment]
Mistakenly removed the assignment. 
Curious to know why level 1. thanks.

**Comment by Chaitalishetty** [comment]
> Mistakenly removed the assignment. Curious to know why level 1. thanks.
As it is about responsiveness i gave level 1. Don't worry about that if the pr is good then will give level 2.

**Comment by khushimarothi** [comment]
There is a huge mess since there is only one css file for the whole website. Kindly separate them for different pages by commenting.
