### ISSUE TITLE
Add other project cards on PROJECTS page

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [HackClubRAIT/HackClubRAIT.github.io#167]
**Is your feature request related to a problem? Please describe.**
The projects page currently has only 4 project cards.
I believe the projects page should display all the projects under this program.

**Describe the solution you'd like**
I offer to add cards for other projects which are not currently added.

### Are you participating under any open-source program? ### 
HackClubRAIT

**Comment by Chaitalishetty** [comment]
@Soumya-Kushwaha Those projects are the ones from HackclubRAIT. You dont need to add anything.
