### ISSUE TITLE
Fix Margin in team page.

### ISSUE THREAD

**Issue by siddhi-244** [HackClubRAIT/HackClubRAIT.github.io#84]
**Is your feature request related to a problem? Please describe.**
Margin in teams page icons is not looking good.

**Describe the solution you'd like**
i would like to solve this.

### Are you participating under any open-source program? ### 
( fill NA if none )
hacktoberfest

**Comment by Chaitalishetty** [comment]
@siddhi-244 Assigning this issue to you . Happy Coding !
