### ISSUE TITLE
hover effect on cards of contributors would look good. 

### ISSUE THREAD

**Issue by HardikSJain** [HackClubRAIT/HackClubRAIT.github.io#94]
**Is your feature request related to a problem? Please describe.**
hover effect on cards of contributors would look good like changing the scale slightly to zoom in the card on which our cursor is on.

**Describe the solution you'd like**
adding transition to css properties of those cards

### Are you participating under any open-source program? ### 
hacktoberfest

**Comment by ok524** [comment]
I would like to take this!
